dist: trusty
language: elixir
elixir:
  - 1.5.3
otp_release:
  - 18.3
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis
